// <auto-generated />
namespace InternTrack.Core.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddIntern : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIntern));
        
        string IMigrationMetadata.Id
        {
            get { return "202305071736152_AddIntern"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
